# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='Gender',
            field=models.IntegerField(),
        ),
    ]
