# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0002_stockinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HistoryTime', models.DateTimeField()),
                ('Highest_value', models.FloatField()),
                ('Lowest_value', models.FloatField()),
                ('StockID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.StockInfo')),
            ],
        ),
    ]
